<%@ page language="VB" autoeventwireup="false" masterpagefile="~/hacims_masterpage_admin.master" inherits="Administrator_Admin_dmc_phyelements, App_Web_0xn5azrs" enableEventValidation="false" theme="theme_hacims" viewStateEncryptionMode="Never" maintainScrollPositionOnPostBack="true" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="Server">
    <asp:Label ID="Label_message" runat="server" CssClass="err"></asp:Label>
    <div class="bxmain">
        <table width="100%" border="0" cellpadding="0" cellspacing="0" class="tbl_form">
            <tr>
                <td align="right" width="20%">
                    Main Group Part :
                </td>
                <td width="25%">
                    <asp:DropDownList AutoPostBack="True" DataTextField="MG_Name" DataValueField="MG_Code"
                        ID="DropDownListMGroup" runat="server" DataSourceID="SqlDataSourceMGroup">
                    </asp:DropDownList>
                </td>
                <td align="right" width="25%">
                    Element Name :
                </td>
                <td>
                    <asp:TextBox ID="TextBoxElementName" runat="server"></asp:TextBox>
                </td>
            </tr>
            <tr>
                <td align="right">
                    Element DataType :
                </td>
                <td>
                    <asp:DropDownList DataTextField="DataTye" DataValueField="DataTye" ID="DropDownListDataType"
                        runat="server" DataSourceID="SqlDataSourceDatatype">
                    </asp:DropDownList>
                </td>
                <td align="right">
                    Before Language :
                </td>
                <td>
                    <asp:TextBox ID="TextBoxBefore" runat="server"></asp:TextBox>
                </td>
            </tr>
            <tr>
                <td align="right">
                    Group Para Start :
                </td>
                <td>
                    <asp:TextBox ID="TextBoxParaStart" runat="server"></asp:TextBox>
                </td>  
                <td align="right">
                    After Language :
                </td>
                <td>
                    <asp:TextBox ID="TextBoxAfter" runat="server"></asp:TextBox>
                </td>
            </tr>
            
            <tr>
                <td align="right">
                    Min :
                </td>
                <td>
                    <asp:TextBox ID="txtMin" runat="server"></asp:TextBox>
                </td>
                
                <td align="right">
                    Max :
                </td>
                <td>
                    <asp:TextBox ID="txtMax" runat="server"></asp:TextBox>
                </td>
            </tr>
            <tr>
                <td colspan="4" align="center">
                    <asp:Button ID="ButtonSave" runat="server" Text="Save" />
                    <asp:Label CssClass="err" ID="Label1" runat="server"></asp:Label>
                </td>
            </tr>
        </table>
    </div>
    <br />
    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True"
        DataKeyNames="e_Code" DataSourceID="SqlDataSourceForGridView" Width="100%">
        <FooterStyle CssClass="GridPager"></FooterStyle>
        <Columns>
            <asp:CommandField ShowEditButton="True" />
            <asp:BoundField DataField="MG_Name" SortExpression="MG_Name" HeaderText="Main Group Name"
                ReadOnly="True"></asp:BoundField>
            <asp:TemplateField HeaderText="Element Name" SortExpression="e_Name">
                <EditItemTemplate>
                    <asp:TextBox ID="TextBox1" runat="server" Text='<%# Bind("e_Name") %>'></asp:TextBox>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="Label2" runat="server" Text='<%# Bind("e_Name") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Field Type" SortExpression="e_Field_Type">
                <EditItemTemplate>
                    <asp:DropDownList ID="DropDownList1" runat="server" DataSourceID="SqlDataSourceDatatype1"
                        DataTextField="DataTye" DataValueField="DataTye" Width="168px" SelectedValue='<%# Bind("e_Field_Type") %>'>
                    </asp:DropDownList>
                    <asp:SqlDataSource ID="SqlDataSourceDatatype1" runat="server" ConnectionString="<%$ ConnectionStrings:Treatment_AdminConnectionString %>"
                        ProviderName="<%$ ConnectionStrings:Treatment_AdminConnectionString.ProviderName %>"
                        SelectCommand="SELECT [DataTye] FROM [Admin_ASP_Controls]"></asp:SqlDataSource>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="Label1" runat="server" Text='<%# Bind("e_Field_Type") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:BoundField ReadOnly="True" DataField="e_Code" InsertVisible="False" SortExpression="e_Code"
                HeaderText="Element Code"></asp:BoundField>
            <asp:TemplateField HeaderText="Priority" SortExpression="Priority">
                <EditItemTemplate>
                    <asp:TextBox ID="TextBoxPriority" runat="server" Text='<%# Bind("Priority") %>'></asp:TextBox>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="Label3" runat="server" Text='<%# Bind("Priority") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>            
            <asp:BoundField DataField="Min" HeaderText="Min" SortExpression="Min" />
            <asp:BoundField DataField="Max" HeaderText="Max" SortExpression="Max" />
        </Columns>
        <RowStyle CssClass="GridItem"></RowStyle>
        <HeaderStyle CssClass="GridHeader"></HeaderStyle>
        <AlternatingRowStyle CssClass="GridAltItem"></AlternatingRowStyle>
    </asp:GridView>
    <br />
    <asp:SqlDataSource ID="SqlDataSourceForGridView" runat="server" ConnectionString="<%$ ConnectionStrings:Treatment_AdminConnectionString %>"
        DeleteCommand="DELETE FROM admin_Phy_Exam_Elements WHERE (e_Code = @e_Code)"
        SelectCommand="SELECT admin_Phy_Exam_MainGroup.MG_Name, admin_Phy_Exam_Elements.e_Code, admin_Phy_Exam_Elements.e_Name, admin_Phy_Exam_Elements.e_Field_Type, admin_Phy_Exam_Elements.Priority, admin_Phy_Exam_Elements.Secondary_Control, admin_Phy_Exam_Elements.Min, admin_Phy_Exam_Elements.Max FROM admin_Phy_Exam_MainGroup INNER JOIN Admin_Phy_Exam_Elememt_Assign_To_Group ON admin_Phy_Exam_MainGroup.MG_Code = Admin_Phy_Exam_Elememt_Assign_To_Group.MG_Code INNER JOIN admin_Phy_Exam_Elements ON Admin_Phy_Exam_Elememt_Assign_To_Group.e_Code = admin_Phy_Exam_Elements.e_Code WHERE (Admin_Phy_Exam_Elememt_Assign_To_Group.MG_Code = @MG_Code)"
        UpdateCommand="UPDATE admin_Phy_Exam_Elements SET e_Name = @e_Name, e_Field_Type = @e_Field_Type, Priority = @Priority WHERE (e_Code = @e_Code)"
        ProviderName="<%$ ConnectionStrings:Treatment_AdminConnectionString.ProviderName %>">
        <DeleteParameters>
            <asp:ControlParameter PropertyName="SelectedValue" Name="e_Code" ControlID="GridView1">
            </asp:ControlParameter>
        </DeleteParameters>
        <SelectParameters>
            <asp:ControlParameter PropertyName="SelectedValue" Name="MG_Code" ControlID="DropDownListMGroup">
            </asp:ControlParameter>
        </SelectParameters>
        <UpdateParameters>
            <asp:ControlParameter ControlID="HiddenFieldEName" Name="e_Name" PropertyName="Value" />
            <asp:ControlParameter ControlID="HiddenFieldEType" Name="e_Field_Type" PropertyName="Value" />
            <asp:ControlParameter ControlID="HiddenFieldPriority" Name="Priority" PropertyName="Value" />
            <asp:ControlParameter ControlID="GridView1" Name="e_Code" PropertyName="SelectedValue" />
        </UpdateParameters>
    </asp:SqlDataSource>
    <asp:SqlDataSource ID="SqlDataSourceMGroup" runat="server" ConnectionString="<%$ ConnectionStrings:Treatment_AdminConnectionString %>"
        SelectCommand="SELECT MG_Code, MG_Name FROM admin_Phy_Exam_MainGroup&#13;&#10;order by MG_Name "
        ProviderName="<%$ ConnectionStrings:Treatment_AdminConnectionString.ProviderName %>">
    </asp:SqlDataSource>
    <asp:SqlDataSource ID="SqlDataSourceDatatype" runat="server" ConnectionString="<%$ ConnectionStrings:Treatment_AdminConnectionString %>"
        ProviderName="<%$ ConnectionStrings:Treatment_AdminConnectionString.ProviderName %>"
        SelectCommand="SELECT DataTye FROM Admin_ASP_Controls"></asp:SqlDataSource>
    <asp:SqlDataSource ID="SqlDataSourceSaveInfo" runat="server" ConnectionString="<%$ ConnectionStrings:Treatment_AdminConnectionString %>"
        InsertCommand="[Admin_Insert_History_Element]" InsertCommandType="StoredProcedure"
        ProviderName="<%$ ConnectionStrings:Treatment_AdminConnectionString.ProviderName %>">
        <InsertParameters>
            <asp:ControlParameter ControlID="DropDownListMGroup" Name="MG_Code" PropertyName="SelectedValue"
                Type="Int32" />
            <asp:ControlParameter ControlID="TextBoxElementName" Name="e_Name" PropertyName="Text"
                Type="String" />
            <asp:ControlParameter ControlID="DropDownListDataType" Name="e_Field_Type" PropertyName="SelectedValue"
                Type="String" />
        </InsertParameters>
    </asp:SqlDataSource>
    <asp:HiddenField ID="HiddenFieldEName" runat="server" />
    <asp:HiddenField ID="HiddenFieldEType" runat="server" />
    <asp:HiddenField ID="HiddenFieldEle_Code" runat="server" />
    <asp:SqlDataSource ID="SqlDataSourceSaveInfo1" runat="server" ConnectionString="<%$ ConnectionStrings:Treatment_AdminConnectionString %>"
        InsertCommand="INSERT INTO Admin_Phy_Exam_Elememt_Assign_To_Group (MG_Code, e_Code, Alias, e_id) VALUES (@MG_Code, @e_Code, @Alias, @e_id)"
        ProviderName="<%$ ConnectionStrings:Treatment_AdminConnectionString.ProviderName %>">
        <InsertParameters>
            <asp:ControlParameter ControlID="DropDownListMGroup" Name="MG_Code" PropertyName="SelectedValue" />
            <asp:ControlParameter ControlID="HiddenFieldEle_Code" Name="e_Code" PropertyName="Value" />
            <asp:ControlParameter ControlID="TextBoxElementName" Name="Alias" PropertyName="Text" />
            <asp:ControlParameter ControlID="HiddenFieldE_Id" Name="e_id" PropertyName="Value" />
        </InsertParameters>
    </asp:SqlDataSource>
    <asp:HiddenField ID="HiddenFieldE_Id" runat="server" />
    <asp:HiddenField ID="HiddenFieldPriority" runat="server" />
</asp:Content>
